

site_name: YOLOv8 Explainer
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dev-rajk
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Spritan
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/TheJamesWillett
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/willettjames/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy 2024 Proyash Paban Sarma Borah and Devraj Kashyap

plugins: 
 - search: null 
 - mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src]

nav:
  - Home: index.md
  - Detailed Documentation : functions.md
  - References: references.md
